import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';
import '../../../../app/theme/app_colors.dart';
import '../../../../app/theme/app_radius.dart';
import '../../../../app/theme/app_spacing.dart';
import '../../../../app/theme/app_typography.dart';
import '../../../../shared/models/activity_category.dart';
import '../../../../shared/models/priority.dart';
import '../../../../shared/widgets/primary_button.dart';
import '../../../activities/domain/models/activity.dart';
import '../../../activities/presentation/providers/activity_provider.dart';

class AISuggestionCardData {
  final String title;
  final String timeRange;
  final String category;
  final String reason;

  AISuggestionCardData({
    required this.title,
    required this.timeRange,
    required this.category,
    required this.reason,
  });
}

class AIPlannerScreen extends ConsumerStatefulWidget {
  const AIPlannerScreen({super.key});

  @override
  ConsumerState<AIPlannerScreen> createState() => _AIPlannerScreenState();
}

class _AIPlannerScreenState extends ConsumerState<AIPlannerScreen> {
  final _promptController = TextEditingController();
  bool _isGenerating = false;
  List<AISuggestionCardData>? _suggestions;

  @override
  void dispose() {
    _promptController.dispose();
    super.dispose();
  }

  Future<void> _askAi(String prompt) async {
    _promptController.text = prompt;
    setState(() {
      _isGenerating = true;
      _suggestions = null;
    });

    await Future.delayed(const Duration(milliseconds: 1000));

    if (!mounted) return;

    if (prompt.toLowerCase().contains('exam') || prompt.toLowerCase().contains('study')) {
      _suggestions = [
        AISuggestionCardData(
          title: 'DSA: Dynamic Programming Review',
          timeRange: '16:00 – 17:30',
          category: 'Study',
          reason: 'Scheduled during your 2.5h afternoon free-time slot before gym.',
        ),
        AISuggestionCardData(
          title: 'Database Mock Quiz & Practice',
          timeRange: '20:00 – 21:00',
          category: 'Study',
          reason: 'Review queries and indexing before Friday deadline.',
        ),
      ];
    } else {
      _suggestions = [
        AISuggestionCardData(
          title: 'Deep Work: Project Implementation',
          timeRange: '12:30 – 14:00',
          category: 'Study',
          reason: 'Capitalizing on uninterrupted midday energy window.',
        ),
        AISuggestionCardData(
          title: 'Evening Refresh & Walk',
          timeRange: '17:30 – 18:15',
          category: 'Health',
          reason: 'Prevents study fatigue between classes and project sprint.',
        ),
      ];
    }

    setState(() => _isGenerating = false);
  }

  Future<void> _applyPlan() async {
    if (_suggestions == null) return;
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);

    for (final s in _suggestions!) {
      final times = s.timeRange.split('–');
      final sTime = times[0].trim();
      final eTime = times.length > 1 ? times[1].trim() : '17:00';

      final activity = Activity(
        id: const Uuid().v4(),
        userId: 'user_1',
        title: s.title,
        description: 'Generated by AI Planner: ${s.reason}',
        date: today,
        startTime: sTime,
        endTime: eTime,
        durationMinutes: 90,
        category: s.category == 'Study' ? ActivityCategory.study : ActivityCategory.health,
        priority: Priority.high,
        status: ActivityStatus.pending,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );
      await ref.read(activityNotifierProvider.notifier).addActivity(activity);
    }

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('AI Plan successfully added to your daily schedule!')),
      );
      setState(() => _suggestions = null);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('AI Planner', style: AppTypography.heading3.copyWith(fontWeight: FontWeight.bold)),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(AppSpacing.xxl),
        child: Column(
          children: [
            // Top Assistant Icon
            Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: AppColors.primaryContainer.withAlpha(80),
                shape: BoxShape.circle,
              ),
              child: const Icon(Icons.auto_awesome, size: 48, color: AppColors.primary),
            ),
            const SizedBox(height: AppSpacing.xl),
            Text(
              'Ask AI for a better plan',
              style: AppTypography.heading2,
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: AppSpacing.xs),
            Text(
              'Get personalized suggestions, optimize your schedule, and stay on track.',
              style: AppTypography.body.copyWith(color: AppColors.textSecondaryLight),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: AppSpacing.xxl),

            // Prompt Chips
            Wrap(
              spacing: 8,
              runSpacing: 8,
              alignment: WrapAlignment.center,
              children: [
                _promptChip('Optimize my today'),
                _promptChip('Study plan for exam'),
                _promptChip('Improve my productivity'),
                _promptChip('Find best free-time slots'),
              ],
            ),
            const SizedBox(height: AppSpacing.xxl),

            // Input Bar
            Container(
              decoration: BoxDecoration(
                color: Theme.of(context).cardColor,
                borderRadius: AppRadius.radiusLg,
                border: Border.all(color: Theme.of(context).dividerColor),
              ),
              child: Row(
                children: [
                  Expanded(
                    child: TextField(
                      controller: _promptController,
                      decoration: const InputDecoration(
                        hintText: 'Type your routine request...',
                        border: InputBorder.none,
                        contentPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                      ),
                      onSubmitted: (val) {
                        if (val.trim().isNotEmpty) _askAi(val.trim());
                      },
                    ),
                  ),
                  IconButton(
                    icon: _isGenerating
                        ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2))
                        : const Icon(Icons.arrow_upward, color: AppColors.primary),
                    onPressed: _isGenerating
                        ? null
                        : () {
                            if (_promptController.text.trim().isNotEmpty) {
                              _askAi(_promptController.text.trim());
                            }
                          },
                  ),
                ],
              ),
            ),
            const SizedBox(height: AppSpacing.xxl),

            // Suggestions Card Section
            if (_suggestions != null) ...[
              Align(
                alignment: Alignment.centerLeft,
                child: Text('Suggested Schedule Adjustments', style: AppTypography.heading3),
              ),
              const SizedBox(height: AppSpacing.md),
              ..._suggestions!.map((s) => _buildSuggestionTile(s)),
              const SizedBox(height: AppSpacing.lg),
              PrimaryButton(
                text: 'Confirm & Apply to Schedule',
                icon: Icons.check,
                onPressed: _applyPlan,
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _promptChip(String label) {
    return ActionChip(
      label: Text(label),
      backgroundColor: AppColors.primaryContainer.withAlpha(50),
      side: const BorderSide(color: AppColors.primaryLight, width: 0.8),
      onPressed: () => _askAi(label),
    );
  }

  Widget _buildSuggestionTile(AISuggestionCardData data) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Theme.of(context).cardColor,
        borderRadius: AppRadius.radiusLg,
        border: Border.all(color: AppColors.primary.withAlpha(60)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(data.title, style: AppTypography.bodyMedium.copyWith(fontWeight: FontWeight.bold)),
              Text(data.timeRange, style: AppTypography.small.copyWith(color: AppColors.primary, fontWeight: FontWeight.bold)),
            ],
          ),
          const SizedBox(height: 4),
          Text(data.reason, style: AppTypography.small.copyWith(color: AppColors.textSecondaryLight)),
        ],
      ),
    );
  }
}
